# Generated by Django 5.1.7 on 2025-06-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='is_commented',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
