# Generated by Django 5.1.7 on 2025-04-03 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eshopapis.product'),
        ),
    ]
