# Generated by Django 5.1.7 on 2025-05-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_payment_id',
            field=models.CharField(default=12345, max_length=50),
            preserve_default=False,
        ),
    ]
