# Generated by Django 5.1.7 on 2025-05-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='owner_ident',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='owner_name',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='store_address',
            field=models.CharField(default=123, max_length=400),
            preserve_default=False,
        ),
    ]
