# Generated by Django 5.1.7 on 2025-04-08 00:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationseller',
            name='temp_store_logo',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
