# Generated by Django 5.1.7 on 2025-04-08 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapis', '0002_alter_verificationseller_temp_store_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationseller',
            name='employee',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='employee', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verificationseller',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
