# Generated by Django 5.1.7 on 2025-05-15 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapis', '0002_category_logo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='store',
            unique_together={('owner',)},
        ),
    ]
