# Generated by Django 5.1.7 on 2025-06-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapis', '0002_orderdetail_is_commented_alter_user_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
