# Generated by Django 5.1.7 on 2025-05-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapis', '0002_store_owner_ident_store_owner_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationseller',
            name='temp_owner_ident',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verificationseller',
            name='temp_owner_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verificationseller',
            name='temp_store_address',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
