# Generated by Django 5.1.7 on 2025-04-08 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapis', '0003_verificationseller_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationseller',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='verificationseller',
            name='temp_store_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
