# Generated by Django 5.1.7 on 2025-06-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapis', '0003_payment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ship_address',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
