# Generated by Django 5.1.7 on 2025-05-28 15:00

import cloudinary.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapis', '0003_alter_store_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversasion',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='productrating',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='store',
        ),
        migrations.AddField(
            model_name='commentuser',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentuser',
            name='like',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order_status',
            field=models.CharField(choices=[('PE', 'PENDING'), ('SU', 'SUCCESS'), ('SH', 'SHIPPING'), ('CA', 'CANCEL')], default='PE', max_length=2),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_orders', to='eshopapis.store'),
        ),
        migrations.AddField(
            model_name='productrating',
            name='rating',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='productrating',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentseller',
            name='rep_cmt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rep_cmt', to='eshopapis.commentuser'),
        ),
        migrations.AlterField(
            model_name='commentuser',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='eshopapis.productvariant'),
        ),
        migrations.CreateModel(
            name='CommentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_list', to='eshopapis.commentuser')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=50)),
                ('order_payment_id', models.CharField(max_length=50)),
                ('amount', models.FloatField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('portal_payment', models.CharField(default='MOMO', max_length=30)),
                ('payment_status', models.BooleanField(default=False)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='eshopapis.order')),
            ],
        ),
        migrations.CreateModel(
            name='StoreRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshopapis.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.RemoveField(
            model_name='productrating',
            name='count',
        ),
        migrations.RemoveField(
            model_name='productrating',
            name='rating_star',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
