# Generated by Django 5.1.7 on 2025-05-04 13:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapis', '0003_verificationseller_temp_owner_ident_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationseller',
            name='temp_store_logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
