# Generated by Django 5.1.7 on 2025-06-06 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapis', '0004_order_ship_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ship_address',
            new_name='shipping_address',
        ),
    ]
