# Generated by Django 5.1.7 on 2025-04-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapis', '0004_alter_verificationseller_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationseller',
            name='temp_store_name',
            field=models.CharField(max_length=255),
        ),
    ]
