# Generated by Django 5.1.7 on 2025-05-04 13:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapis', '0004_alter_verificationseller_temp_store_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationseller',
            name='temp_store_logo',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
