# Generated by Django 5.1.7 on 2025-04-08 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapis', '0005_alter_verificationseller_temp_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eshopapis.store'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='attributes',
            field=models.ManyToManyField(blank=True, null=True, to='eshopapis.attributevalue'),
        ),
    ]
