# Generated by Django 5.1.7 on 2025-04-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapis', '0006_alter_product_store_alter_productvariant_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(blank=True, to='eshopapis.product'),
        ),
    ]
